config/routes.rb
Rails.application.routes.draw do
  resources :families

  # Redirect to localhost from 127.0.0.1 to use same IP address with Vite server
  constraints(host: "127.0.0.1") do
    get "(*path)", to: redirect { |params, req| "#{req.protocol}localhost:#{req.port}/#{params[:path]}" }
  end
  resources :attendance_reports
  resources :group_members
  resources :groups
  resources :team_members
  resources :teams
  resources :members
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "dashboard#index"

  get "/login" => "sessions#new", as: :login
end

app/models/family.rb
class Family < ApplicationRecord
  has_many :members, dependent: :nullify
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  before_action :set_family, only: %i[ show edit update destroy ]

  # GET /families or /families.json
  def index
    @families = Family.all
  end

  # GET /families/1 or /families/1.json
  def show
  end

  # GET /families/new
  def new
    @family = Family.new
  end

  # GET /families/1/edit
  def edit
  end

  # POST /families or /families.json
  def create
    @family = Family.new(family_params)

    respond_to do |format|
      if @family.save
        format.html { redirect_to @family, notice: "Family was successfully created." }
        format.json { render :show, status: :created, location: @family }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /families/1 or /families/1.json
  def update
    respond_to do |format|
      if @family.update(family_params)
        format.html { redirect_to @family, notice: "Family was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @family }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /families/1 or /families/1.json
  def destroy
    @family.destroy!

    respond_to do |format|
      format.html { redirect_to families_path, notice: "Family was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_family
      @family = Family.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def family_params
      params.expect(family: [ :name ])
    end
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/views/families/_family.html.erb
<div id="<%= dom_id family %>" class="w-full sm:w-auto my-5">
  <div class="card flex flex-col h-full">
    <div class="card-title"><%= family.name %></div>

  <div class="flow-y flex-1 min-h-0">
      <div>
        <strong class="block font-medium mb-1">Members</strong>
        <ul id="family-members-<%= family.id %>" class="list-disc pl-5">
          <% family.members.order(:last_name, :first_name).each do |m| %>
            <li class="text-sm text-gray-700"><%= m.full_name %></li>
          <% end %>
        </ul>
      </div>
      <div>
    </div>
    <% if local_assigns[:show_actions] %>
      <div class="mt-4 flex flex-wrap items-center space-x-2">
        <%= link_to "Show", family, class: "text-sm rounded-md px-3 py-1 bg-gray-100 hover:bg-gray-50 font-medium" %>
        <%= link_to "Edit", edit_family_path(family), class: "text-sm rounded-md px-3 py-1 bg-gray-100 hover:bg-gray-50 font-medium" %>
        <%= button_to "Destroy", family, method: :delete, form: { data: { turbo_confirm: "Are you sure?" } }, class: "text-sm rounded-md px-3 py-1 text-white bg-red-600 hover:bg-red-500 font-medium" %>
      </div>
    <% end %>
  </div>
</div>

app/views/families/_form.html.erb
<%= form_with(model: family) do |form| %>
  <% if family.errors.any? %>
    <div style="color: red" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(family.errors.count, "error") %> prohibited this family from being saved:</h2>

      <ul>
        <% family.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": family.errors[:name].none?, "border-red-400 focus:outline-red-600": family.errors[:name].any?}] %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/families/edit.html.erb
<% content_for :title, "Editing family" %>

<h1>Editing family</h1>

<%= render "form", family: @family %>

<br>

<div>
  <%= link_to "Show this family", @family %> |
  <%= link_to "Back to families", families_path %>
</div>

app/views/families/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Families" %>

<h1>Families</h1>

<div id="families">
  <% @families.each do |family| %>
    <%= render family, show_actions: true %>
  <% end %>
</div>

<%= link_to "New family", new_family_path %>

app/views/families/new.html.erb
<% content_for :title, "New family" %>

<h1>New family</h1>

<%= render "form", family: @family %>

<br>

<div>
  <%= link_to "Back to families", families_path %>
</div>

app/views/families/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @family %>

<div>
  <%= link_to "Edit this family", edit_family_path(@family) %> |
  <%= link_to "Back to families", families_path %>

  <%= button_to "Destroy this family", @family, method: :delete %>
</div>