config/routes.rb
Rails.application.routes.draw do
  resources :families

  # Redirect to localhost from 127.0.0.1 to use same IP address with Vite server
  constraints(host: "127.0.0.1") do
    get "(*path)", to: redirect { |params, req| "#{req.protocol}localhost:#{req.port}/#{params[:path]}" }
  end
  resources :attendance_reports
  resources :group_members
  resources :groups
  resources :team_members
  resources :teams
  resources :members
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "dashboard#index"

  get "/login" => "sessions#new", as: :login
end

app/models/team_member.rb
class TeamMember < ApplicationRecord
  belongs_to :team
  belongs_to :member
end

app/controllers/team_members_controller.rb
class TeamMembersController < ApplicationController
  before_action :set_team_member, only: %i[ show edit update destroy ]

  # GET /team_members or /team_members.json
  def index
    @team_members = TeamMember.all
  end

  # GET /team_members/1 or /team_members/1.json
  def show
  end

  # GET /team_members/new
  def new
    @team_member = TeamMember.new
  end

  # GET /team_members/1/edit
  def edit
  end

  # POST /team_members or /team_members.json
  def create
    @team_member = TeamMember.new(team_member_params)

    respond_to do |format|
      if @team_member.save
        @team = @team_member.team
        @member = @team_member.member
        format.turbo_stream
        format.html { redirect_to @team_member, notice: "Team member was successfully created." }
        format.json { render :show, status: :created, location: @team_member }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @team_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /team_members/1 or /team_members/1.json
  def update
    respond_to do |format|
      if @team_member.update(team_member_params)
        format.html { redirect_to @team_member, notice: "Team member was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @team_member }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @team_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /team_members/1 or /team_members/1.json
  def destroy
    @team = @team_member.team
    @member = @team_member.member
    @team_member.destroy!

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to team_members_path, notice: "Team member was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team_member
      @team_member = TeamMember.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def team_member_params
      params.expect(team_member: [ :team_id, :member_id, :status, :role])
    end
end

app/helpers/team_members_helper.rb
module TeamMembersHelper
end

app/views/team_members/_form.html.erb
<%= form_with(model: team_member, class: "contents") do |form| %>
  <% if team_member.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(team_member.errors.count, "error") %> prohibited this team_member from being saved:</h2>

      <ul class="list-disc ml-6">
        <% team_member.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :team_id, "Team" %>
    <%= form.collection_select :team_id, Team.order(:name), :id, :name, { prompt: "Select a team" }, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", { "border-gray-400 focus:outline-blue-600": team_member.errors[:team_id].none?, "border-red-400 focus:outline-red-600": team_member.errors[:team_id].any? }] %>
  </div>

  <div class="my-5">
    <%= form.label :member_id, "Member" %>
    <%= form.collection_select :member_id, Member.order(:first_name), :id, :first_name, { prompt: "Select a member" }, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", { "border-gray-400 focus:outline-blue-600": team_member.errors[:member_id].none?, "border-red-400 focus:outline-red-600": team_member.errors[:member_id].any? }] %>
  </div>

  <div class="my-5">
    <%= form.label :status %>
    <%= form.number_field :status, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": team_member.errors[:status].none?, "border-red-400 focus:outline-red-600": team_member.errors[:status].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/team_members/_team_member.html.erb
<div id="<%= dom_id team_member %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Team:</strong>
    <%= team_member.team.name %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Member:</strong>
    <%= team_member.member.full_name %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Status:</strong>
    <%= team_member.status %>
  </div>
</div>

app/views/team_members/create.turbo_stream.erb
<%= turbo_stream.append "team-members-#{@team.id}" do %>
  <%= render "shared/member_list_item", member: @member, team_membership: @team_member %>
<% end %>

<%= turbo_stream.append "flash-messages" do %>
  <div id="notice" class="py-2 px-3 bg-green-50 mb-2 text-green-500 font-medium rounded-md inline-block">Member added</div>
<% end %>

app/views/team_members/destroy.turbo_stream.erb
<%= turbo_stream.remove "member-#{@member.id}" %>

<%= turbo_stream.append "flash-messages" do %>
  <div id="notice" class="py-2 px-3 bg-yellow-50 mb-2 text-yellow-700 font-medium rounded-md inline-block">Member removed</div>
<% end %>

app/views/team_members/edit.html.erb
<% content_for :title, "Editing team member" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing team member</h1>

  <%= render "form", team_member: @team_member %>

  <%= link_to "Show this team member", @team_member, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to team members", team_members_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/team_members/index.html.erb
<% content_for :title, "Team members" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Team members</h1>
    <%= link_to "New team member", new_team_member_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="team_members" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @team_members.any? %>
      <% @team_members.each do |team_member| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render team_member %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", team_member, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_team_member_path(team_member), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", team_member, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No team members found.</p>
    <% end %>
  </div>
</div>

app/views/team_members/new.html.erb
<% content_for :title, "New team member" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New team member</h1>

  <%= render "form", team_member: @team_member %>

  <%= link_to "Back to team members", team_members_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/team_members/show.html.erb
<% content_for :title, "Showing team member" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing team member</h1>

  <%= render @team_member %>

  <%= link_to "Edit this team member", edit_team_member_path(@team_member), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to team members", team_members_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this team member", @team_member, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>